### ISSUE TITLE
Fix PDF y axis lower limit at zero

### ISSUE THREAD

**Issue by e-pet** [distribution-explorer/distribution-explorer.github.io#2]
Hi there,

thank you for an amazing tool! :-) 

I have one minor suggestion: might it be a good idea to fix the y axis lower limit at 0? E.g., in the following case (Gamma distribution), I was quite confused for a while before I noticed that the lower limit is 0.04 and not 0.

![image](https://github.com/distribution-explorer/distribution-explorer.github.io/assets/1774207/2d9d3ee9-cc9a-49fb-b8b9-0187b0aa3806)

**Comment by justinbois** [comment]
This is a very good suggestion! I will implement and deploy this very soon!

**Comment by e-pet** [comment]
Awesome, thank you!

**Comment by justinbois** [comment]
Done!
